service: myserverlessproject
app: myserverlessproject
# org: hungngo22
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  profile: serverlessUser
  ecr:
    images:
      # Replace with your actual Docker image URI and tag
      appimage:
        uri: [ID_AWSUSER].dkr.ecr.us-east-1.amazonaws.com/natural-disaster-image:latest

functions:
  myserverlessproject:
    # handler: handler.main
    image:
      uri: [ID_AWSUSER].dkr.ecr.us-east-1.amazonaws.com/natural-disaster-image:latest  # If image is in ECR
    timeout: 900
    memorySize: 2048
    events:
      - s3:
          bucket: myserverlessproject-serverlessdeploymentbucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: disasters/


