service: myserverlessproject
app: myserverlessproject
org: hungngo22

frameworkVersion: "3"

provider:
  name: aws
  profile: serverlessUser
  runtime: python3.10
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  predict:
    handler: handler.main
    environment:
      IMAGE_URI: "767397951463.dkr.ecr.us-east-1.amazonaws.com/natural-disaster-image:latest"
      BUCKET_ARN: "arn:aws:s3:::myserverlessproject-serverlessdeploymentbucket"

    events:
      - s3:
          bucket: myserverlessproject-serverlessdeploymentbucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: disasters/
# custom:
#   pythonRequirements:
#     dockerizePip: true
#     dockerFile: ./Dockerfile
# plugins:
#   - serverless-python-requirements
