service: myserverlessproject
app: myserverlessproject
# org: hungngo22
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-better-credentials
  - serverless-dotenv-plugin

provider:
  name: aws
  profile: ${env:PROFILE_NAME}
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${env:BUCKET_NAME}/disasters/*'
  ecr:
    images:
      appimage:
        path: ./
  s3:
    bucketOne:
      name: ${env:BUCKET_NAME}

functions:
  myserverlessproject:
    # handler: handler.main
    image:
      name: appimage
    timeout: 900
    memorySize: 2048
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: disasters/


